import { LinearClient } from '@linear/sdk';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

// Load environment variables from .env file
dotenv.config();

const LINEAR_API_KEY = process.env.LINEAR_API_KEY as string;
const LINEAR_TEAM_ID = process.env.LINEAR_TEAM_ID as string;

if (!LINEAR_API_KEY || !LINEAR_TEAM_ID) {
    console.error('ERROR: LINEAR_API_KEY and LINEAR_TEAM_ID must be set in the .env file.');
    process.exit(1);
}

// Initialize the Linear API client
const linearClient = new LinearClient({ apiKey: LINEAR_API_KEY });

// Type definition for a Nuclei JSON output entry
interface NucleiResult {
    "template-id": string;
    info: {
        name: string;
        severity: string;
        description?: string;
    };
    "matched-at": string;
    "extracted-results"?: string[];
}

function getTimestampString(): string {
    const now = new Date();
    const pad = (num: number) => String(num).padStart(2, '0');
    
    const year = now.getFullYear();
    const month = pad(now.getMonth() + 1);
    const day = pad(now.getDate());
    const hours = pad(now.getHours());
    const minutes = pad(now.getMinutes());
    const seconds = pad(now.getSeconds());
    
    return `scan_${year}-${month}-${day}_${hours}-${minutes}-${seconds}`;
}

/**
 * Extract hostname from a URL string.
 * Falls back to the full string if parsing fails.
 */
function extractHostname(url: string): string {
    try {
        return new URL(url).hostname;
    } catch {
        return url;
    }
}

/**
 * Build a short, dedup-friendly issue title.
 * Format: [Nuclei] <Finding Name> – <hostname>
 */
function buildTitle(finding: NucleiResult): string {
    const hostname = extractHostname(finding["matched-at"]);
    return `[Nuclei] ${finding.info.name} – ${hostname}`;
}

/**
 * Build a structured issue description using the standard template.
 * See: docs/eint-103-nuclei-pipeline.md §6 (Description Template)
 */
function buildDescription(finding: NucleiResult): string {
    const hostname = extractHostname(finding["matched-at"]);
    const extracted = finding["extracted-results"]
        ? finding["extracted-results"].join('\n')
        : 'None';
    const description = finding.info.description || 'No description available.';

    return `## Vulnerability Report

| Field | Value |
|---|---|
| **Finding** | ${finding.info.name} |
| **Severity** | ${finding.info.severity.toUpperCase()} |
| **Target** | ${finding["matched-at"]} |
| **Hostname** | ${hostname} |
| **Template** | ${finding["template-id"]} |

### Description
${description}

### Extracted Data
${extracted}

---
*Auto-generated by nuclei-to-linear.ts*`;
}

async function run() {
    // Accept file path from CLI argument or default to "results.json"
    const resultsPath = path.resolve(process.cwd(), process.argv[2] || 'results.json');
    
    if (!fs.existsSync(resultsPath)) {
        console.error(`ERROR: Nuclei results file not found: ${resultsPath}`);
        console.error(`Usage: npx ts-node upload/nuclei-to-linear.ts <path-to-results.json>`);
        process.exit(1);
    }

    // Nuclei exports either a JSON array (-json-export) or JSON Lines (-jsonl)
    const fileContent = fs.readFileSync(resultsPath, 'utf-8');
    let findings: NucleiResult[] = [];
    
    try {
        // Attempt 1: Standard JSON (array or single object)
        const parsed = JSON.parse(fileContent);
        findings = Array.isArray(parsed) ? parsed : [parsed];
    } catch (e) {
        // Attempt 2: JSON Lines fallback
        const lines = fileContent.split('\n').filter(line => line.trim() !== '');
        for (const line of lines) {
            try { findings.push(JSON.parse(line)); } catch (err) {}
        }
    }
    
    // Safety check: filter out malformed or empty entries
    const validFindings = findings.filter(f => f && f.info && f.info.severity);
    
    // Route: critical/high/medium/low → Linear tickets; info → local report only
    const ticketFindings = validFindings.filter(f =>
        ['critical', 'high', 'medium', 'low'].includes(f.info.severity.toLowerCase())
    );
    const infoFindings = validFindings.filter(f => f.info.severity.toLowerCase() === 'info');

    // ─── 1. Create versioned output folder & save files ───
    const timestamp = getTimestampString();
    const outputDir = path.resolve(process.cwd(), 'outputs', timestamp);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // Copy raw results into versioned folder
    fs.copyFileSync(resultsPath, path.join(outputDir, 'results.json'));
    console.log(`📦 Saved raw scan results to: outputs/${timestamp}/results.json`);

    // Write info findings to run-specific recon report
    let mdContent = `# 🕵️ Reconnaissance Summary\n\n**Run Timestamp:** ${timestamp}\n\n`;
    if (infoFindings.length > 0) {
        mdContent += `| Template | Target | Description |\n|---|---|---|\n`;
        for (const finding of infoFindings) {
            mdContent += `| ${finding["template-id"]} | ${finding["matched-at"]} | ${finding.info.name} |\n`;
        }
    } else {
        mdContent += `*No informational findings were detected in this run.*\n`;
    }
    fs.writeFileSync(path.join(outputDir, 'recon_summary.md'), mdContent);
    console.log(`✅ Saved run summary to: outputs/${timestamp}/recon_summary.md`);

    // ─── 2. Process findings → Linear tickets ───
    console.log(`🚀 Processing ${ticketFindings.length} actionable findings for Linear...`);
    
    // Fetch team metadata: states, labels
    const team = await linearClient.team(LINEAR_TEAM_ID);
    const teamStates = await team.states();
    const teamLabels = await team.labels();

    // Find or create the nuclei-scan label
    let nucleiLabel = teamLabels.nodes.find(l => l.name === 'nuclei-scan');
    if (!nucleiLabel) {
        console.log(`🏷️  Creating nuclei-scan label...`);
        const result = await linearClient.createIssueLabel({
            teamId: LINEAR_TEAM_ID,
            name: 'nuclei-scan',
            color: '#e74c3c',
        });
        nucleiLabel = (await result.issueLabel)!;
    }

    // Resolve workflow states
    const backlogState = teamStates.nodes.find(s => s.type === 'backlog');
    const completedState = teamStates.nodes.find(s => s.type === 'completed');

    // Fetch existing active issues for deduplication and auto-close
    const existingIssues = await linearClient.issues({
        filter: { team: { id: { eq: LINEAR_TEAM_ID } }, state: { type: { neq: "completed" } } }
    });

    const activeNucleiIssues = existingIssues.nodes.filter(issue => issue.title.startsWith('[Nuclei] '));
    const currentTicketTitles = ticketFindings.map(f => buildTitle(f));

    // ─── A. Auto-Close: resolve tickets for vulnerabilities no longer detected ───
    for (const issue of activeNucleiIssues) {
        if (!currentTicketTitles.includes(issue.title)) {
            console.log(`🧹 Vulnerability no longer detected: "${issue.title}". Resolving...`);
            if (completedState) {
                try {
                    await linearClient.updateIssue(issue.id, { stateId: completedState.id });
                    console.log(`✅ Automatically resolved: "${issue.title}"`);
                } catch (error) {
                    console.error(`❌ Failed to resolve: "${issue.title}":`, error);
                }
            } else {
                console.warn(`⚠️ Could not find a 'completed' state to close: "${issue.title}"`);
            }
        }
    }

    // ─── B. Create new tickets for detected vulnerabilities ───
    for (const finding of ticketFindings) {
        const title = buildTitle(finding);
        
        // Deduplication: skip if an active issue with the same title exists
        const isDuplicate = existingIssues.nodes.some(issue => issue.title === title);
        if (isDuplicate) {
            console.log(`⏭️  Skipping duplicate: ${title}`);
            continue;
        }

        const description = buildDescription(finding);

        // Map severity → Linear priority (using Linear's actual terminology)
        // 1: Urgent, 2: High, 3: Medium, 4: Low
        let priority = 0; 
        switch (finding.info.severity.toLowerCase()) {
            case 'critical': priority = 1; break;  // Urgent
            case 'high':     priority = 2; break;  // High
            case 'medium':   priority = 3; break;  // Medium
            case 'low':      priority = 4; break;  // Low
        }

        try {
            await linearClient.createIssue({
                teamId: LINEAR_TEAM_ID,
                title: title,
                description: description,
                priority: priority,
                stateId: backlogState?.id,
                labelIds: nucleiLabel ? [nucleiLabel.id] : [],
            });
            console.log(`🎟️  Created ticket: ${title}`);
        } catch (error) {
            console.error(`❌ Failed to create ticket for ${title}:`, error);
        }
    }
}

run().catch(console.error);
